### ISSUE TITLE
Wrong link in README

### ISSUE THREAD

**Issue by BorntraegerMarc** [e-id-admin/open-source-community#8]
I believe the link on [line #30 in the README](https://github.com/e-id-admin/open-source-community/blame/0a12344a636dcbe12cc6eefd3004f27e3c32454b/README.md#L30) should point to the issues in this repository and not to `governance-sounding-board`, right?

Or maybe I misunderstood the context...

**Comment by christianheimann** [comment]
Absolutely! Thank you for the indication.
